package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        /* Notre liste de "users" est déjà générée à la L.9 en tant qu'attribut de la présente classe via l'appel de
         * la méthode generateUsers() qui retourne la liste des FAKE_USERS depuis la classe FakeApiServiceGenerator.
         * Ici, notre méthode se charge donc de retourner cette liste de "users".*/
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        /*Dans la classe User il y a une methode random() qui retourne un user tiré aléatoirement de la liste FAKE_USERS_RANDOM
         *Ici, il nous reste  donc à ajouter cet user aléatoire à notre liste de users*/
        users.add(User.random());
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
    }
}
